export enum ActivityTypes {
  CommitCommentEvent = "CommitCommentEvent",
  CreateEvent = "CreateEvent",
  DeleteEvent = "DeleteEvent",
  ForkEvent = "ForkEvent",
  GollumEvent = "GollumEvent",
  IssueCommentEvent = "IssueCommentEvent",
  IssuesEvent = "IssuesEvent",
  MemberEvent = "MemberEvent",
  PublicEvent = "PublicEvent",
  PullRequestEvent = "PullRequestEvent",
  PullRequestReviewCommentEvent = "PullRequestReviewCommentEvent",
  PushEvent = "PushEvent",
  ReleaseEvent = "ReleaseEvent",
  SponsorshipEvent = "SponsorshipEvent",
  WatchEvent = "WatchEvent",
};
